form_fieldsgroup:
    resource: "@FormBundle/Resources/config/routing/fieldsgroup.yml"
    prefix:   /fieldsgroup

form_field:
    resource: "@FormBundle/Resources/config/routing/field.yml"
    prefix:   /field

form_form:
    resource: "@FormBundle/Resources/config/routing/form.yml"
    prefix:   /form

form_homepage:
    path:     /hello/{name}
    defaults: { _controller: FormBundle:Default:index }
